### ISSUE TITLE
Copy of Create Activity Diagrams for User Stories in Epic 1: User Account Creation & Management

### ISSUE THREAD

**Issue by agoluoglu** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#19]
Make Activity Diagrams for each of the following user stories:
- [ ] User Story 1.1: Create Account
- [ ] User Story 1.2: Login
- [ ] User Story 1.3: Reset Password
- [ ] User Story 1.4: Change Password
- [ ] User Story 1.5: Delete Account
